---
version: '2'
services:

  grpc-server:
    image: grpc-test:latest 
    hostname: grpc-server
    command: ./server -h 0.0.0.0 -p 50051
    deploy:
      replicas: 4


  grpc-client:
    image: grpc-test:latest 
    hostname: grpc-client
    command: ./client -h grpc-server -p 50051 -t 500
    deploy:
      replicas: 4




