---
version: '2'
services:

  grpc-server:
    image: grpc-test:latest 
    hostname: grpc-server
    #container_name: grpc-server
    command: ./server -h 0.0.0.0 -p 50051
    # ports:
    #     - "50051:50050"
    deploy:
      replicas: 4


  grpc-client:
    image: grpc-test:latest 
    hostname: grpc-client
    #container_name: grpc-client
    command: ./client -h grpc-server -p 50051
    deploy:
      replicas: 4




